site_name: Semantic Browser Documentation
site_description: Comprehensive documentation for the Semantic Browser for AI Agents
site_author: Semantic Browser Team
site_url: https://gianlucamazza.github.io/semanticbrowser/
repo_name: gianlucamazza/semanticbrowser
repo_url: https://github.com/gianlucamazza/semanticbrowser
edit_uri: edit/main/docs/

theme:
  name: material
  language: en
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate

plugins:
  - search

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - meta
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: gianlucamazza
      repo: semanticbrowser
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md
  - User Guide:
      - Quick Start: user-guide/quickstart.md
      - Docker Setup: user-guide/docker-setup.md
      - Core Operations: user-guide/core-operations.md
      - Browser Automation: user-guide/browser-automation.md
      - Examples: user-guide/examples/README.md
  - Developer Guide:
      - Architecture: developer-guide/architecture.md
      - Testing: developer-guide/testing.md
      - Contributing: developer-guide/contributing.md
      - Performance Tuning: developer-guide/performance-tuning.md
      - Production Deployment: developer-guide/production-deployment.md
      - MCP Extension: developer-guide/mcp-extension-guide.md
  - API Reference: api/README.md
  - Reference:
      - Authentication: reference/authentication.md
      - Configuration: reference/configuration.md
      - ML Models: reference/ml-models.md
      - Observability: reference/observability.md
      - Security: reference/security.md
      - Code of Conduct: reference/code-of-conduct.md
      - Changelog: reference/changelog.md
      - ML ONNX Guide: reference/ml-onnx-guide.md
      - Seccomp: reference/seccomp.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/gianlucamazza/semanticbrowser
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com
  generator: false

copyright: Copyright &copy; 2025 Semantic Browser Team - Licensed under MIT
